/**
 * @file bms4_x_cannetv1_08.c
 *
 * @brief This source file was generated by cantools version 42.0.3 Sun Jul 12 14:09:01 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "bms4_x_cannetv1_08.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int bms4_x_cannetv1_08_l2_b_01_vextremum_pack(
    uint8_t *dst_p,
    const struct bms4_x_cannetv1_08_l2_b_01_vextremum_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->l2_b_u_cell_hi1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->l2_b_u_cell_hi1, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->l2_b_u_cell_lo1, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->l2_b_u_cell_lo1, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->l2_b_u_mdl1, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->l2_b_u_mdl1, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->l2_b_u_cell_hi_nr1, 0u, 0x1fu);
    dst_p[6] |= pack_left_shift_u8(src_p->l2_b_u_cell_l_nr1, 5u, 0xe0u);
    dst_p[7] |= pack_right_shift_u8(src_p->l2_b_u_cell_l_nr1, 3u, 0x03u);
    dst_p[7] |= pack_left_shift_u8(src_p->l2_b_life_u_extremum1, 4u, 0xf0u);

    return (8);
}

int bms4_x_cannetv1_08_l2_b_01_vextremum_unpack(
    struct bms4_x_cannetv1_08_l2_b_01_vextremum_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->l2_b_u_cell_hi1 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->l2_b_u_cell_hi1 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->l2_b_u_cell_lo1 = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->l2_b_u_cell_lo1 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->l2_b_u_mdl1 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->l2_b_u_mdl1 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->l2_b_u_cell_hi_nr1 = unpack_right_shift_u8(src_p[6], 0u, 0x1fu);
    dst_p->l2_b_u_cell_l_nr1 = unpack_right_shift_u8(src_p[6], 5u, 0xe0u);
    dst_p->l2_b_u_cell_l_nr1 |= unpack_left_shift_u8(src_p[7], 3u, 0x03u);
    dst_p->l2_b_life_u_extremum1 = unpack_right_shift_u8(src_p[7], 4u, 0xf0u);

    return (0);
}

int bms4_x_cannetv1_08_l2_b_01_vextremum_init(struct bms4_x_cannetv1_08_l2_b_01_vextremum_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct bms4_x_cannetv1_08_l2_b_01_vextremum_t));
    msg_p->l2_b_life_u_extremum1 = 15.0;

    return 0;
}

uint16_t bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi1_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi1_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi1_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65.535));
}

uint16_t bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_lo1_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_lo1_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_lo1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_lo1_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65.535));
}

uint16_t bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_mdl1_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_mdl1_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_mdl1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_mdl1_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 655.35));
}

uint8_t bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi_nr1_encode(double value)
{
    return (uint8_t)(value);
}

double bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi_nr1_decode(uint8_t value)
{
    return ((double)value);
}

bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi_nr1_is_in_range(uint8_t value)
{
    return (value <= 24u);
}

bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi_nr1_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 24.0));
}

uint8_t bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_l_nr1_encode(double value)
{
    return (uint8_t)(value);
}

double bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_l_nr1_decode(uint8_t value)
{
    return ((double)value);
}

bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_l_nr1_is_in_range(uint8_t value)
{
    return (value <= 24u);
}

bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_l_nr1_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 24.0));
}

uint8_t bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_life_u_extremum1_encode(double value)
{
    return (uint8_t)(value);
}

double bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_life_u_extremum1_decode(uint8_t value)
{
    return ((double)value);
}

bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_life_u_extremum1_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_life_u_extremum1_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 15.0));
}

int bms4_x_cannetv1_08_l2_b_01_v_sig1_pack(
    uint8_t *dst_p,
    const struct bms4_x_cannetv1_08_l2_b_01_v_sig1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->l2_b_u_cell1_nr01, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->l2_b_u_cell1_nr01, 8u, 0x7fu);
    dst_p[1] |= pack_left_shift_u8(src_p->l2_b_u_cell1_nr01_vld, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u16(src_p->l2_b_u_cell1_nr02, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->l2_b_u_cell1_nr02, 8u, 0x7fu);
    dst_p[3] |= pack_left_shift_u8(src_p->l2_b_u_cell1_nr02_vld, 7u, 0x80u);
    dst_p[4] |= pack_left_shift_u16(src_p->l2_b_u_cell1_nr03, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->l2_b_u_cell1_nr03, 8u, 0x7fu);
    dst_p[5] |= pack_left_shift_u8(src_p->l2_b_u_cell1_nr03_vld, 7u, 0x80u);
    dst_p[6] |= pack_left_shift_u16(src_p->l2_b_u_cell1_nr04, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->l2_b_u_cell1_nr04, 8u, 0x7fu);
    dst_p[7] |= pack_left_shift_u8(src_p->l2_b_u_cell1_nr04_vld, 7u, 0x80u);

    return (8);
}

int bms4_x_cannetv1_08_l2_b_01_v_sig1_unpack(
    struct bms4_x_cannetv1_08_l2_b_01_v_sig1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->l2_b_u_cell1_nr01 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->l2_b_u_cell1_nr01 |= unpack_left_shift_u16(src_p[1], 8u, 0x7fu);
    dst_p->l2_b_u_cell1_nr01_vld = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->l2_b_u_cell1_nr02 = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->l2_b_u_cell1_nr02 |= unpack_left_shift_u16(src_p[3], 8u, 0x7fu);
    dst_p->l2_b_u_cell1_nr02_vld = unpack_right_shift_u8(src_p[3], 7u, 0x80u);
    dst_p->l2_b_u_cell1_nr03 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->l2_b_u_cell1_nr03 |= unpack_left_shift_u16(src_p[5], 8u, 0x7fu);
    dst_p->l2_b_u_cell1_nr03_vld = unpack_right_shift_u8(src_p[5], 7u, 0x80u);
    dst_p->l2_b_u_cell1_nr04 = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->l2_b_u_cell1_nr04 |= unpack_left_shift_u16(src_p[7], 8u, 0x7fu);
    dst_p->l2_b_u_cell1_nr04_vld = unpack_right_shift_u8(src_p[7], 7u, 0x80u);

    return (0);
}

int bms4_x_cannetv1_08_l2_b_01_v_sig1_init(struct bms4_x_cannetv1_08_l2_b_01_v_sig1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct bms4_x_cannetv1_08_l2_b_01_v_sig1_t));

    return 0;
}

uint16_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 32.767));
}

uint8_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_vld_encode(double value)
{
    return (uint8_t)(value);
}

double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_vld_decode(uint8_t value)
{
    return ((double)value);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_vld_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_vld_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint16_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 32.767));
}

uint8_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_vld_encode(double value)
{
    return (uint8_t)(value);
}

double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_vld_decode(uint8_t value)
{
    return ((double)value);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_vld_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_vld_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint16_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 32.767));
}

uint8_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_vld_encode(double value)
{
    return (uint8_t)(value);
}

double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_vld_decode(uint8_t value)
{
    return ((double)value);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_vld_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_vld_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint16_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 32.767));
}

uint8_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_vld_encode(double value)
{
    return (uint8_t)(value);
}

double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_vld_decode(uint8_t value)
{
    return ((double)value);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_vld_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_vld_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}
