/**
 * @file bms4_x_cannetv1_08.h
 *
 * @brief This header file was generated by cantools version 42.0.3 Sun Jul 12 14:09:01 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef BMS4_X_CANNETV1_08_H
#define BMS4_X_CANNETV1_08_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define BMS4_X_CANNETV1_08_L2_B_01_VEXTREMUM_FRAME_ID (0x1810f401u)
#define BMS4_X_CANNETV1_08_L2_B_01_V_SIG1_FRAME_ID (0x1811f401u)

/* Frame lengths in bytes. */
#define BMS4_X_CANNETV1_08_L2_B_01_VEXTREMUM_LENGTH (8u)
#define BMS4_X_CANNETV1_08_L2_B_01_V_SIG1_LENGTH (8u)

/* Extended or standard frame types. */
#define BMS4_X_CANNETV1_08_L2_B_01_VEXTREMUM_IS_EXTENDED (1)
#define BMS4_X_CANNETV1_08_L2_B_01_V_SIG1_IS_EXTENDED (1)

/* Frame cycle times in milliseconds. */
#define BMS4_X_CANNETV1_08_L2_B_01_VEXTREMUM_CYCLE_TIME_MS (100u)
#define BMS4_X_CANNETV1_08_L2_B_01_V_SIG1_CYCLE_TIME_MS (100u)

/* Signal choices. */


/* Frame Names. */
#define BMS4_X_CANNETV1_08_L2_B_01_VEXTREMUM_NAME "L2B_01Vextremum"
#define BMS4_X_CANNETV1_08_L2_B_01_V_SIG1_NAME "L2B_01VSig1"

/* Signal Names. */
#define BMS4_X_CANNETV1_08_L2_B_01_VEXTREMUM_L2_B_U_CELL_HI1_NAME "L2B_UCellHi1"
#define BMS4_X_CANNETV1_08_L2_B_01_VEXTREMUM_L2_B_U_CELL_LO1_NAME "L2B_UCellLo1"
#define BMS4_X_CANNETV1_08_L2_B_01_VEXTREMUM_L2_B_U_MDL1_NAME "L2B_UMdl1"
#define BMS4_X_CANNETV1_08_L2_B_01_VEXTREMUM_L2_B_U_CELL_HI_NR1_NAME "L2B_UCellHiNr1"
#define BMS4_X_CANNETV1_08_L2_B_01_VEXTREMUM_L2_B_U_CELL_L_NR1_NAME "L2B_UCellLNr1"
#define BMS4_X_CANNETV1_08_L2_B_01_VEXTREMUM_L2_B_LIFE_U_EXTREMUM1_NAME "L2B_LifeUExtremum1"
#define BMS4_X_CANNETV1_08_L2_B_01_V_SIG1_L2_B_U_CELL1_NR01_NAME "L2B_UCell1Nr01"
#define BMS4_X_CANNETV1_08_L2_B_01_V_SIG1_L2_B_U_CELL1_NR01_VLD_NAME "L2B_UCell1Nr01Vld"
#define BMS4_X_CANNETV1_08_L2_B_01_V_SIG1_L2_B_U_CELL1_NR02_NAME "L2B_UCell1Nr02"
#define BMS4_X_CANNETV1_08_L2_B_01_V_SIG1_L2_B_U_CELL1_NR02_VLD_NAME "L2B_UCell1Nr02Vld"
#define BMS4_X_CANNETV1_08_L2_B_01_V_SIG1_L2_B_U_CELL1_NR03_NAME "L2B_UCell1Nr03"
#define BMS4_X_CANNETV1_08_L2_B_01_V_SIG1_L2_B_U_CELL1_NR03_VLD_NAME "L2B_UCell1Nr03Vld"
#define BMS4_X_CANNETV1_08_L2_B_01_V_SIG1_L2_B_U_CELL1_NR04_NAME "L2B_UCell1Nr04"
#define BMS4_X_CANNETV1_08_L2_B_01_V_SIG1_L2_B_U_CELL1_NR04_VLD_NAME "L2B_UCell1Nr04Vld"

/**
 * Signals in message L2B_01Vextremum.
 *
 * All signal values are as on the CAN bus.
 */
struct bms4_x_cannetv1_08_l2_b_01_vextremum_t {
    /**
     * 1LECUɵߵѹ
     *
     * Range: 0..65535 (0..65.535 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t l2_b_u_cell_hi1;

    /**
     * 1LECUɲɵ͵ѹ
     *
     * Range: 0..65535 (0..65.535 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t l2_b_u_cell_lo1;

    /**
     * 1LECUģѹ
     *
     * Range: 0..65535 (0..655.35 V)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t l2_b_u_mdl1;

    /**
     * 1LECUߵѹڱ
     *
     * Range: 0..24 (0..24 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t l2_b_u_cell_hi_nr1;

    /**
     * 1LECU͵ѹڱ
     *
     * Range: 0..24 (0..24 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t l2_b_u_cell_l_nr1;

    /**
     * ֵ
     *
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t l2_b_life_u_extremum1;
};

/**
 * Signals in message L2B_01VSig1.
 *
 * All signal values are as on the CAN bus.
 */
struct bms4_x_cannetv1_08_l2_b_01_v_sig1_t {
    /**
     * 1Ӱ01ŵѹ
     *
     * Range: 0..32767 (0..32.767 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t l2_b_u_cell1_nr01;

    /**
     * 1Ӱ01ŵѹЧλ1ΪЧ
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t l2_b_u_cell1_nr01_vld;

    /**
     * 1Ӱ02ŵѹ
     *
     * Range: 0..32767 (0..32.767 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t l2_b_u_cell1_nr02;

    /**
     * 1Ӱ02ŵѹЧλ1ΪЧ
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t l2_b_u_cell1_nr02_vld;

    /**
     * 1Ӱ03ŵѹ
     *
     * Range: 0..32767 (0..32.767 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t l2_b_u_cell1_nr03;

    /**
     * 1Ӱ03ŵѹЧλ1ΪЧ
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t l2_b_u_cell1_nr03_vld;

    /**
     * 1Ӱ04ŵѹ
     *
     * Range: 0..32767 (0..32.767 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t l2_b_u_cell1_nr04;

    /**
     * 1Ӱ04ŵѹЧλ1ΪЧ
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t l2_b_u_cell1_nr04_vld;
};

/**
 * Pack message L2B_01Vextremum.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int bms4_x_cannetv1_08_l2_b_01_vextremum_pack(
    uint8_t *dst_p,
    const struct bms4_x_cannetv1_08_l2_b_01_vextremum_t *src_p,
    size_t size);

/**
 * Unpack message L2B_01Vextremum.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int bms4_x_cannetv1_08_l2_b_01_vextremum_unpack(
    struct bms4_x_cannetv1_08_l2_b_01_vextremum_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from L2B_01Vextremum.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int bms4_x_cannetv1_08_l2_b_01_vextremum_init(struct bms4_x_cannetv1_08_l2_b_01_vextremum_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi1_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi1_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi1_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_lo1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_lo1_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_lo1_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_lo1_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_mdl1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_mdl1_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_mdl1_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_mdl1_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi_nr1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi_nr1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi_nr1_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_hi_nr1_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_l_nr1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_l_nr1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_l_nr1_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_u_cell_l_nr1_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_life_u_extremum1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_life_u_extremum1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_life_u_extremum1_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_vextremum_l2_b_life_u_extremum1_is_in_phys_range(double value);

/**
 * Pack message L2B_01VSig1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int bms4_x_cannetv1_08_l2_b_01_v_sig1_pack(
    uint8_t *dst_p,
    const struct bms4_x_cannetv1_08_l2_b_01_v_sig1_t *src_p,
    size_t size);

/**
 * Unpack message L2B_01VSig1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int bms4_x_cannetv1_08_l2_b_01_v_sig1_unpack(
    struct bms4_x_cannetv1_08_l2_b_01_v_sig1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from L2B_01VSig1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int bms4_x_cannetv1_08_l2_b_01_v_sig1_init(struct bms4_x_cannetv1_08_l2_b_01_v_sig1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_vld_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_vld_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_vld_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr01_vld_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_vld_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_vld_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_vld_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr02_vld_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_vld_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_vld_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_vld_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr03_vld_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_vld_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_vld_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_vld_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bms4_x_cannetv1_08_l2_b_01_v_sig1_l2_b_u_cell1_nr04_vld_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
